"use client";
// components/Icon.tsx — maps original <Icon name="..."/> calls onto lucide-react

import {
  LayoutDashboard, Users, Receipt, User, ArrowRightLeft, Wallet,
  Container, CircleDollarSign, BarChart3, Clock, Settings, UserCircle,
  Search, Bell, Plus, Minus, Pencil, Info, ChevronDown, ChevronRight,
  X, Check, Sparkles, Shield, Crown, Coins, Trophy, Target, BookOpen,
  Gift, PartyPopper, Home, Banknote, Download, Upload, ListFilter,
  Grid3x3, List, MessageSquare, ChevronUp, ArrowUpDown, MoreHorizontal,
  Utensils, Car, ShoppingBag, Gamepad2, ReceiptText, Bed, Briefcase,
  GraduationCap, Building2, ShoppingCart, Mail, Phone, Image,
  UserPlus, Moon, Sun, SplitSquareHorizontal, Percent, Share2,
  Camera, Calendar, Hash, Lock, TriangleAlert, Trash2,
  type LucideProps,
} from "lucide-react";

const map: Record<string, React.ComponentType<LucideProps>> = {
  dashboard: LayoutDashboard,
  groups: Users,
  expense: Receipt,
  friends: User,
  settle: ArrowRightLeft,
  wallet: Wallet,
  jars: Container,
  debt: CircleDollarSign,
  reports: BarChart3,
  activity: Clock,
  settings: Settings,
  account: UserCircle,
  search: Search,
  bell: Bell,
  plus: Plus,
  minus: Minus,
  edit: Pencil,
  info: Info,
  chev: ChevronDown,
  chevR: ChevronRight,
  x: X,
  check: Check,
  sparkle: Sparkles,
  shield: Shield,
  crown: Crown,
  coin: Coins,
  trophy: Trophy,
  receipt: Receipt,
  target: Target,
  book: BookOpen,
  gift: Gift,
  party: PartyPopper,
  home: Home,
  money: Banknote,
  download: Download,
  upload: Upload,
  filter: ListFilter,
  grid: Grid3x3,
  list: List,
  chat: MessageSquare,
  chev2: ChevronUp,
  sortArrows: ArrowUpDown,
  dots: MoreHorizontal,
  fork: Utensils,
  car: Car,
  bag: ShoppingBag,
  controller: Gamepad2,
  bill: ReceiptText,
  bed: Bed,
  more: MoreHorizontal,
  briefcase: Briefcase,
  graduation: GraduationCap,
  ball: Trophy,
  office: Building2,
  "shopping-cart": ShoppingCart,
  mail: Mail,
  phone: Phone,
  image: Image,
  userPlus: UserPlus,
  moon: Moon,
  sun: Sun,
  share: Share2,
  "split-equal": SplitSquareHorizontal,
  "split-pct": Percent,
  "split-share": Share2,
  bars: BarChart3,
  camera: Camera,
  calendar: Calendar,
  hash: Hash,
  lock: Lock,
  alertTriangle: TriangleAlert,
  trash: Trash2,
};

interface IconProps extends Omit<LucideProps, "size"> {
  name: string;
  size?: number;
}

export default function Icon({ name, size = 16, strokeWidth = 1.7, ...rest }: IconProps) {
  const C = map[name];
  if (!C) return null;
  return <C size={size} strokeWidth={strokeWidth} {...rest} />;
}
